### ISSUE TITLE
Nested ordered/ unordered lists do not start at 1

### ISSUE THREAD

**Issue by Nadine2016** [colinwilson/lotusdocs#33]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

When using nested lists, such as an ordered list within an ordered list, or an unordered list within an ordered list, the sublists do not display proper bullets/ numbers. 

Example 1: Unordered list within ordered list > no bullet points are displayed

<img width="490" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/0eb099af-4f02-4f0b-b68c-1f58c46b6baf">

Example 2: Ordered list within ordered list > Substeps do not start at 1

<img width="420" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/f38023d9-c4be-44f4-8435-c2c16f9e46b0">

### Expected behavior

Display unordered lists as bullet points when nested in ordered lists. 
Start counting from 1 for ordered lists that are nested in another ordered list. 

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 116
```

**Comment by colinwilson** [comment]
Fixed by 9695c5c

**Comment by colinwilson** [comment]
Thanks 👍

**Comment by Nadine2016** [comment]
Thank you @colinwilson I just tried your change and it works for nested ordered lists as shown in the image: 

<img width="373" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/aeeb37c1-c67c-4a36-bbf4-8828512f61f0">


But bulleted lists within steps still do not show up properly 

<img width="390" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/35651f45-2bf4-4cf7-a1ea-450a3195d0c9">


Code would be
```
1. Step 1
2. Step 2 
    * Bullet point 1
    * Bullet point 2
```

**Comment by colinwilson** [comment]
Damn! Thank you. Re-opened.

**Comment by colinwilson** [comment]
Fixed by 499567e

Should be ok now.

**Edit**: Nested Ordered lists inside Unordered lists needs fixing too.

**Comment by colinwilson** [comment]
Ok. Finally resolved this. Will update once I've cleaned the CSS

**Comment by Nadine2016** [comment]
thank you so much! I tried it locally and it works :)

**Comment by Nadine2016** [comment]
@colinwilson fyi, I added another counter-reset element to the `ul` element because it still continued counting after the bulleted list. so for example if I had this: 

```
1. Step 1
   * Bullet point 1
   * Bullet point 2
2. Step 2
```

Then the second step would not have number 2, but number 4. 

I changed it to this here and that seems to work. 

```
ul {
        li::before {
            content: "";
            width: 6px;
            height: 6px;
            left: 8px;
            top: 10px;
            padding: 0;
            border-radius: 30%;
            background: var(--gray-500);
        }
        counter-reset: listitem;
    }
```

**Comment by colinwilson** [comment]
Thank you. 👍

I'll test this with what I've done so far. 

The coming update should allow `<ul>`'s nested inside `<ol>`'s (and vice versa) no matter how many levels of mixed nesting there are.

**Comment by colinwilson** [comment]
Fixed by 3f7463e
